igel_panel:
    resource: "@IgelPanelBundle/Controller/"
    type:     annotation
    prefix:   /

admin_main:
    resource: "@AdminMainBundle/Controller/"
    type:     annotation
    prefix:   /

cyl_main:
    resource: "@IgelMainBundle/Controller/"
    type:     annotation
    prefix:   /