igel_panel:
    resource: "@IgelPanelBundle/Controller/"
    type:     annotation
    prefix:   /panel

admin_main:
    resource: "@AdminMainBundle/Controller/"
    type:     annotation
    prefix:   /admin

cyl_main:
    resource: "@IgelMainBundle/Controller/"
    type:     annotation
    prefix:   /