<?php

namespace Igel\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

	public function getUserSearch($sUsername){
		$oQuery = $this->createQueryBuilder('p')
			->select('*')
			->where('p.username like %:username%')
			->setParameter('username', $sUsername)
			->orderBy('p.id', 'asc')
			->getQuery();
		return $oQuery->getResult();
	}
}
