<?php

namespace Igel\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserExtensionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserExtensionTypeRepository extends EntityRepository
{
}
